version: "3"
services:
  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./django_web_app/:/src
    tty: true
    ports:
      - 9000:9000
    depends_on:
      - db
    entrypoint: /src/wait_for_it.sh db:3306 user user
    command: python3 /src/manage.py runserver 0.0.0.0:9000

  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data:/docker-entrypoint-initdb.d
    ports:
      - '3333:3306'

volumes:
  db_data:
    driver: local
