# Generated by Django 3.0.2 on 2020-02-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='text')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
